### ISSUE TITLE
translation is overflown

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [dolanskurd/Al-Mawrid#2]
I am using goldendict & linux. when I search for "quarry" I get this:
![image](https://user-images.githubusercontent.com/1632566/76700924-d2dd3100-66d5-11ea-9854-6fc56ed4b291.png)

there are words missing !

**Comment by 0xdolan** [comment]
It seems the issue is related to CSS. I will try to fix it as soon as had time.

**Comment by khalid-hussain** [comment]
![image](https://user-images.githubusercontent.com/3102714/76797024-9a3d7480-6807-11ea-8c04-92c9a39aaecc.png)

Try using this version: 1.5.0-RC2-372-gc3ff15f

I don't think the problem is with the dictionary since it shows up fine on MDict on Android as well.

![image](https://user-images.githubusercontent.com/3102714/76797273-1afc7080-6808-11ea-94b5-a112bcf782dc.png)

**Comment by Fahad-Alsaidi** [comment]
I am using 1.5.0-RC2-422-g353ea17 build from master
![image](https://user-images.githubusercontent.com/1632566/76817214-adf2d600-681b-11ea-9814-ef1d3c288e70.png)

**Comment by Fahad-Alsaidi** [comment]
I test the dictionary on windows and it seems works fine.It maybe related to Linux & Goldendict?
